### ISSUE TITLE
No lights found

### ISSUE THREAD

**Issue by Andobi** [ristomatti/node-red-contrib-node-lifx#1]
Hi there,
I'm having a couple of issues using node-red-contrib-node-lifx, and I've read a few issues threads here where @ristomatti said that this more up-to-date fork could be better. I'd like to give it a try. I've installed it over the top of the previous module in my user directory .node-red, using npm install github:ristomatti/node-red-contrib-node-lifx, and restarted node red.

My issue is that the server doesn't seem to be functioning, as it cannot find any lights. Even if I put in an ip address in the server config, and a light id (taken from the lifx app info for that bulb) into a node.

What have I missed here?

Cheers,
Andobi

**Comment by ristomatti** [comment]
The most common reason is a firewall blocking UDP traffic. If your Node-RED host has a firewall enabled, try to disable it temporarily and see if that fixes the issue. Another issue could be that the server is in a different subnet than the lights, e.g. server IP address is 192.168.0.xxx and the lights have an IP address on 192.168.50.xxx range.

I hope this helps!

**Comment by ristomatti** [comment]
I read your message again - did it find lights when using the original version of the node? It would sound very odd as there aren't that many changes. Or at least changes related to connectivity as far as I remember.

**Comment by Andobi** [comment]
To be clear, the original code works. But I want to try your fork. Are the issues you mentioned likely to be different with your fork?

**Comment by Andobi** [comment]
Could it be just a lot slower to pick up the list?

**Comment by ristomatti** [comment]
Picking up the list should be as fast or even faster if the light IP's are defined as a comma separate list. My 12 lights get detected in few seconds usually. I wonder if something could have went wrong during the installation. Could you check if your `node_modules/lifx-lan-client` has a dir `lib` in it?

**Comment by ristomatti** [comment]
...actually it should be very unlikely for it to be missing. At some point the package had a postinstall hook that didn't work correctly on all Node versions but it has now been removed.

**Comment by Andobi** [comment]
Yes there is that directory present. Although I had to switch back to the original module as I needed all my automations to run.

**Comment by ristomatti** [comment]
I can try if I can get the issue reproduced by first installing the original version and then installing my fork on top of it.

**Comment by Andobi** [comment]
In fairness I've also tried uninstall of original module and fresh install of your fork. Then I uninstalled that and reinstalled the original, which works again. Your help would be appreciated!

**Comment by ristomatti** [comment]
I'm not sure if it was just coincincence but I was able to somewhat reproduce the issue. Steps I did:
1. Install `node-red-contrib-node-lifx` from the Node-RED palette
2. Add an output node, configure a server, deploy, discover lights and select one and then deploy again
3. Stop Node-RED
4. Run `npm install github:ristomatti/node-red-contrib-node-lifx` under `.node-red`
5. Start Node-RED
6. Open the existing output done, try to discover -> only 3/12 lights were visible

I then deleted the output node and recreated it. After that I was able to discover all my lights. Did you try recreating the Lifx nodes?

**Comment by ristomatti** [comment]
Worth noting - I'm running Node-RED 0.20.8. I haven't yet upgraded to 1.0.x as I'm using a custom theme which I haven't yet updated to work with the new version.

**Comment by ristomatti** [comment]
...now tried with 1.0.5 - no issues for me.

**Comment by Andobi** [comment]
Thanks for looking into this. I'll try this again in a bit. Maybe it was slow discovery (I haven't listed the IPs as haven't needed to) so I might just wait for a while.

**Comment by ristomatti** [comment]
@Andobi Specifying the IP's should speed up discovery so I would recommend doing that anyway. This of course works only if you've assigned a static IP address for them in your router configuration.

**Comment by Andobi** [comment]
> I'm not sure if it was just coincincence but I was able to somewhat reproduce the issue. Steps I did:
> 
> 1. Install `node-red-contrib-node-lifx` from the Node-RED palette
> 2. Add an output node, configure a server, deploy, discover lights and select one and then deploy again
> 3. Stop Node-RED
> 4. Run `npm install github:ristomatti/node-red-contrib-node-lifx` under `.node-red`
> 5. Start Node-RED
> 6. Open the existing output done, try to discover -> only 3/12 lights were visible
> 
> I then deleted the output node and recreated it. After that I was able to discover all my lights. Did you try recreating the Lifx nodes?

Do you think I need to delete and recreate all of them? I have 37 nodes in place.

**Comment by Andobi** [comment]
Well I've tried this. I removed all the nodes and the server config. Turned off node red. Removed the module and also lifx lan client, removed the entry in the config.json. I actually had lifx lan client folder in a number of locations, maybe I have installed globally previously, not sure if that does that. Removed all of them.
Restarted node red to confirm the module was gone. Then shut it down, installed your fork. Set up the server, put in a valid IP address of 10.0.0.57, still no lights found.
I'm going to now repeat the process, to confirm that the original module works.

**Comment by Andobi** [comment]
Confirmed, works straight away. Like you I can only see some of my lights initially, and the others pop up shortly afterwards.

**Comment by ristomatti** [comment]
@Andobi you got it working? Please close the issue if so. :slightly_smiling_face:

**Comment by Andobi** [comment]
No, I confirmed that the original module works straight away. Your fork doesn't for some reason.
What are the differences beteween the lifx-lan-client and the original node-lifx? I assume it doesn't matter that my ip address range is different to yours.

**Comment by ristomatti** [comment]
`lifx-lan-client` is more up-to-date with support to new products but also has some performance tweaks. I can't think of any change that could cause this unfortunately.

Have you changed any settings on the server node btw? Address or broadcast specifically?

**Comment by Andobi** [comment]
No, I didn't change anything, left it at default. I've had to overwrite the products.json as in another thread to get colour control of some of the more recent LIFX products, so I guess I already have the support for new products.
Performance improvements are what I'm looking for. I'm having some issues with keeping my node red in sync with external changes (I'm also trying to move away from external changes!) in that when a bulb is turned on ("on": true, they are already powered) then node red sees this, updates the status, but then shortly afterwards marks it as off again. This could happen another couple of times before the state is finally correct. Do the performance tweaks do anything about this?

**Comment by ristomatti** [comment]
No I'm afraid not. The performance tweaks mainly address the speed of updating multiple lights at the same times (for the changes to be more in sync).

The issue your describing sounds like node-red-contrib-node-lifx's server node would react to a state change occurring through Node-RED but then briefly updating to a value sent by the light (possibly a color state packet already sent). Would this make sense?

I think I've experienced something similar as you described. At one point I created a user interface in Blynk to set light brightness etc. in a different manner than I can do with the official app. The Blynk app communicated with Node-RED to do the changes. It was extremely difficult to prevent the brightness sliders I had created from not jumping around after changing them. I had to use delay nodes to skip statuses for a while and then only update the value in Blynk after the status in Node-RED had stayed still for long enough.

**Comment by ristomatti** [comment]
As a side note - I want to stress I currently have no intention of doing further improvements to node-red-contrib-node-iifx as the original source code is implemented in a manner that doesn't fit to my way of thinking at all. If I ever get frustrated enough of it, I'd rather do a complete rewrite.

**Comment by Andobi** [comment]
Yes, that is what is happening. Thanks for your responses, I will consider other options.

Since you are here and that you mentioned having a role in maintaining the lifx-lan-client, can you say whether setting on/off using setPower is doing only that? In the lifx developer forum they state that using setPower alone will not interrupt transitions that are in effect (e.g. change colour over longer time period) but my experience with this node red module has been that transitions are interrupted.

**Comment by ristomatti** [comment]
> Yes, that is what is happening. Thanks for your responses, I will consider other options.

Good luck! Please drop a comment if you ran across some new and better node for LIFX!

> can you say whether setting on/off using setPower is doing only that? In the lifx developer forum they state that using setPower alone will not interrupt transitions that are in effect (e.g. change colour over longer time period) but my experience with this node red module has been that transitions are interrupted.

My experience is exactly the same. I don't consider it an issue though. On the contratry if I understood you correctly. Wouldn't it be frustrating if you couldn't interrupt a transition? My practical experience is that every command sent will override the previous command.

**Comment by Andobi** [comment]
According to Lifx, a change in power state should not interrupt a transition that is in progress. So a power on/off should allow the transition to continue in the background. 

Yes, if you want to override it with another transition then that should be allowed!

**Comment by ristomatti** [comment]
That is interesting indeed. I think all the commands (on UDP packet level) have a transition time so I would believe it'd just be implicitly 0 ms when simply toggling the power.

**Comment by Andobi** [comment]
I think (but waiting for them to confirm) that even if the power change has a duration set, it should not in itself interrupt the colour change transition in progress. I wonder if the code in use here is doing something differently.

**Comment by ristomatti** [comment]
It's quite some time I've worked more with the code but it should just use the setPower command from the LAN API and nothing else.

Could you describe the issue a bit more in detail? Do you happen to mean for example setting the color to change to red within 10 minutes but then toggling the light off during that? I actually haven't tested what happens then but I will now. :)

**Comment by ristomatti** [comment]
I tried this now with my LIFX CLI client `lifxsh` (https://github.com/ristomatti/lifxsh) which also uses `lifx-lan-client`. At least with it the color transition actually isn't interrupted exactly like LIFX said. I tried setting a white color to transition to red during 2 minutes while toggling it on and off. Each time I toggled it on, the light was in a different state of transition.

The bulb in particular was a several years old LIFX Original. I'll try the same with a newer LIFX Mini bulb. If it works similarly, I'll try this through Node-RED which I didn't yet do out of lazyness. :grin:

**Comment by ristomatti** [comment]
...LIFX Mini works the same. What I see is that `lifx-lan-client` reports the end values already during the transition while it's still ongoing. Of this I'm not surprised at all.

**Comment by ristomatti** [comment]
You might be on for something here. At least with my remote controller the color transition ends. This would indicate that either my Milight hub -> node-red-contrib-node-lifx bridge code always creates a `setColor` packet or that it's actually node-red-contrib-node-lifx's code that does it. I'll try to get myself to investigate this today or tomorrow (no promises)!

**Comment by Andobi** [comment]
Thanks for confirming that the base client code works as expected. From my delve into the node-lifx code (not a js programmer!) I couldn't see any issue other than potentially having duration set, but the lifx lan documentation says [SetPower ](https://lan.developer.lifx.com/docs/light-messages#section-setpower-117) expects a duration anyway.

It would be great if you can look into the node red module also. I'll try to figure out the code myself too, although I'm not used to reading it.

**Comment by ristomatti** [comment]
I found the issue. node-red-contrib-node-lifx seems to always use `setColor` for all changes! You can only find `setColor` implemented here https://github.com/ristomatti/node-red-contrib-node-lifx/blob/master/lib/lifx-light.js

I'll investigate a bit furher on how much work it would take to use `setPower` in case no hue/saturation/kelvin value was included.

**Comment by ristomatti** [comment]
Ah sorry I was a bit hasty. There actually is logic that should take care of this. But I think there might be a bug.

**Comment by Andobi** [comment]
lifx-light.js line 610 to turn light on: sets colour and then sets on. If I read this right, could be my issue.
Line 569 ignores colours for turning the light off (according to comments) so that should be ok.
I also noted in line 318 that possibly an option for {"on": toggle} is there. That could be useful!

**Comment by ristomatti** [comment]
Yep I'm staring at he same lines. But oh boy what spaghetti the whole `LightItem.prototype.setColor` method is...

**Comment by ristomatti** [comment]
This code does not make any sense to me. :joy: I can only imagine why it has to be so complicated. It's very difficult to keep track of the values. At first I thought it might be just a couple of lines of code to call `this.lifx.on/off` if `changedColor` is `false`. But the code set it to `true` even if only brightness is changed.

I'll see if I can do some quick hack to fix this. I don't have enough will power to refactor that mess to something understandable.

**Comment by Andobi** [comment]
Understood! Interestingly I've just confirmed with some trial and error that msg.payload of {"on": "toggle"} seems to work as expected to toggle the power on/off. Quotes needed. But I doubt it solves the problem!

Let me know how you get on with the on/off change with no other changes.

**Comment by ristomatti** [comment]
Don't hold your breath. I haven't done any code in 4 months and I see it has had an effect. :joy:

**Comment by Andobi** [comment]
No worries. At the very least we have confirmed that the issue lies in this modules code. I saw that the original author is not going to develop it further. Probably worth logging the issue there for another dev to pick up (I'm new to github so I just assume it works like that).

**Comment by ristomatti** [comment]
This started bugging me also so I'll try my best to fix this. Debugging my solution at the moment...

**Comment by ristomatti** [comment]
I think I got it fixed. But the question is how could you test this if my fork does not work for you?

BTW. while testing my change I noticed that occasionally the light I've configured is not detected and I need to redeploy. I'm so inpatient I haven't waited if it'd eventually come online though. I've just restarted the flows and it has fixed it.

**Comment by ristomatti** [comment]
@Andobi If you want to give this fork a shot once again, please try if my changes on my bugfix branch solve the issue for you (without causing other regression). If you do, please add comments here: #2 

To install:
```bash
npm install --save ristomatti/node-red-contrib-node-lifx#bug/set-power
```

**Comment by ristomatti** [comment]
My test flow:
```json
[{"id":"9e9f6f52.eae85","type":"node-lifx-in","z":"541dcf12.49751","server":"27ca218e.645aee","name":"lab desk","lightID":"d073d501a6cd","x":490,"y":680,"wires":[]},{"id":"a026db58.7e0578","type":"inject","z":"541dcf12.49751","name":"on","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":680,"wires":[["a835793a.204378"]]},{"id":"a32fce54.1abb5","type":"inject","z":"541dcf12.49751","name":"off","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":740,"wires":[["28297585.a32cda"]]},{"id":"a835793a.204378","type":"template","z":"541dcf12.49751","name":"toggle on","field":"payload","fieldType":"msg","format":"json","syntax":"mustache","template":"\"true\"","output":"json","x":270,"y":680,"wires":[["9e9f6f52.eae85"]]},{"id":"28297585.a32cda","type":"template","z":"541dcf12.49751","name":"toggle off","field":"payload","fieldType":"msg","format":"javascript","syntax":"mustache","template":"\"false\"","output":"json","x":270,"y":740,"wires":[["9e9f6f52.eae85"]]},{"id":"16104363.2e2fad","type":"template","z":"541dcf12.49751","name":"toggle","field":"payload","fieldType":"msg","format":"json","syntax":"mustache","template":"\"toggle\"","output":"json","x":260,"y":620,"wires":[["9e9f6f52.eae85"]]},{"id":"cfb09a11.d10488","type":"inject","z":"541dcf12.49751","name":"toggle","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":620,"wires":[["16104363.2e2fad"]]},{"id":"27ca218e.645aee","type":"node-lifx-server","z":"","name":"Lifx Server","address":"","broadcast":"","lights":"","interval":"1000"}]
```

**Comment by ristomatti** [comment]
While I'm at it, I'll see if I can do something about this light discovery issue as I can easily reproduce it on my laptop and Node-RED 1.0.x. I haven't noticed any issues when using this on my Odroid C2 that's running my home automation.

**Comment by ristomatti** [comment]
@Andobi I believe I fixed the issue with the light discovery. I had by mistake committed a change that stops light discovery process after all predefined lights are found. :facepalm: If none was predefined it seemed to find the lights only intermittently. I personally use this setting as it prevents lights randomly going offline for me. It's a configuration setting I've added to `lifx-lan-client` but the setting is not exposed for `node-red-contrib-node-lifx`. I probably should add it there instead.

I committed the change (16c743cd96e850a8791cafb46cb79a26a775c939) directly to `master` so its also included on my bugfix branch for the setPower issue. Please test again?

**Comment by Andobi** [comment]
Yes, but I will have to wait until tomorrow for a quiet period in my flows. Can you please instruct a noob how to install the relevant version of your fork. 
Sounds promising though, cheers!

**Comment by Andobi** [comment]
Another thing - I have infrared bulbs, I saw that code is there to detect this but I don't think this is exposed in the node red nodes. I might have missed how to check/set it though.

**Comment by ristomatti** [comment]
> EDIT: sorry, I see that you did give instructions above! I'll follow this tomorrow:
npm install --save ristomatti/node-red-contrib-node-lifx#bug/set-power
what does --save do? I read the manual, seemed to be about dependencies. Why is it necessary?

It's not technically necessary in this case actually. `npm` might actually nowadays do that by default. But what it does is save the module name/location to `package.json` in the same folder. Everything that's defined in `package.json` will get automatically installed when you run `npm install`. It's handy if you want to reinstall the same Node-RED nodes to another computer without having to copy the contents of `node_modules`.

> Another thing - I have infrared bulbs, I saw that code is there to detect this but I don't think this is exposed in the node red nodes. I might have missed how to check/set it though.

My last recollection of it is that there was some bug that prevented the IR state from reporting. It might actually even be disabled in the code elsewhere. IMO the feature is pretty useless. At least I have the IR always on when the light is off as it is by default...

**Comment by Andobi** [comment]
Thanks for the explanation. I think I did read that the --save thing happens automatically now.

Regarding the IR, I switch mine off when not in use, otherwise I think it would be on for most of the daytime which seems like a waste of energy. I also only use IR on one bulb where I have a camera, but in the future I'll probably have more cameras so would use more of them. Now I've moved all my automations from the lifx cloud to node-red, except for that one that controls IR based on sunrise/sunset which I can't as it's not a feature of this module.

Thanks for all the help!

**Comment by ristomatti** [comment]
It's always good to save energy of course. Personally I just believe the power consumption has to be pretty neglible as it's very dim for an IR light. If you find the previous two issues fixed, be welcome to create a feature request for the IR toggling and I might take a look at some point.

**Comment by Andobi** [comment]
Ok, will test it tomorrow and report back.

**Comment by Andobi** [comment]
> I think (but waiting for them to confirm) that even if the power change has a duration set, it should not in itself interrupt the colour change transition in progress. 
> […](#)

This has been confirmed in this thread at LIFX. I got some other useful info there like different waveforms can be set.

**Comment by ristomatti** [comment]
lifx-lan-client also has support for setting waveforms but I haven't tested it yet myself nor is it suppored in node-red-contrib-node-lifx unfortunately.

P.S. Clarification just in case regarding your post on the LIFX forum - I'm in no way affiliated with Node-RED (IBM), just a hobbyist.

**Comment by Andobi** [comment]
> P.S. Clarification just in case regarding your post on the LIFX forum - I'm in no way affiliated with Node-RED (IBM), just a hobbyist.

Ah yes, I guess I wasn't sure of the appropriate term!

I should have a chance to test the updates in a couple of hours.

**Comment by Andobi** [comment]
All appears to be working now! I stopped node red, ran the install 
`npm install ristomatti/node-red-contrib-node-lifx#bug/set-power`
restarted node red and my lights were all found immediately, still linked to flows.
I can confirm with injection of colour changes over 30 seconds that injecting {"on": true/false} during this does not interrupt the transition. I've also confirmed that setting a duration for this on/off does not interrupt the transition, as expected from the lifx lan protocol.

Great work, thanks! Can you push your fork to be the main one somehow? I think others would benefit from this.

**Comment by ristomatti** [comment]
Great to hear! The changes have now been merged to the main branch. I'll close this.

**Comment by ristomatti** [comment]
Fixed by 16c743cd96e850a8791cafb46cb79a26a775c939.

**Comment by ristomatti** [comment]
@Andobi Only @jdomei could get this published on NPM (to be installed with `npm install node-red-contrib-node-lifx`). To get this to NPM I would need to come up with a new name and publish that. I might consider publishing this as `node-red-contrib-lifx-lan-client` at some point.

**Comment by Andobi** [comment]
So I guess you add these as pull requests from what I understand and hopefully that will prompt @jdomeij to incorporate them.

I also see that there is a [pull request](https://github.com/jdomeij/node-red-contrib-node-lifx/pull/8#issue-180938933) to add the ability to set the waveform which would be nice for some.

Thanks again. I've now got a much simpler flow for my evening 1 hour change to red, as I don't need to continually set the kitchen lights which are on a motion sensor for on/off.

**Comment by ristomatti** [comment]
I'm pretty sure he has abandoned the project. Perhaps he doesn't have LIFX lights anymore. I can "cherry pick" the PR you linked, thanks for the tip! Maybe you could beta test it if I add the support to my fork? If so, I've created issue #4 to track the progress.

**Comment by ristomatti** [comment]
@Andobi See https://github.com/ristomatti/node-red-contrib-node-lifx/pull/5.
