### ISSUE TITLE
A19 bulb not visible

### ISSUE THREAD

**Issue by zenoran** [ristomatti/node-red-contrib-node-lifx#14]
I have everything working with other bulbs but I have one A19 bulb which doesn't seem to recognize.  I verified the IP and within the router and tried restarting it a few times but no luck getting it to recognize within node-red.  I noticed it might have been added recently within the lifx-lan package so does something have to be done on this end to recognize the bulb as well?

**Comment by zenoran** [comment]
> ...note that if you've got firewall enabled on your computer, it can also block the broadcast packages. In case you do, you'll need to open UDP port 56700 for incoming packages (or allow the app specifically).

Thanks I'll try the CLI out that looks a bit easier to work with. 

I do realize the docker setup is breaking auto discovery since the local docker network isn't the same subnet as my lights are on. I wasn't sure how to fix that issue so I've been adding the IPs manually. If there was a firewall issue I'm sure the other lights wouldn't be working either? 

I'll have some more time to play around with it tomorrow and I'll report back if I find anything. It's just very strange this one model of light is the only issue.

Thanks!

**Comment by ristomatti** [comment]
> I do realize the docker setup is breaking auto discovery since the local docker network isn't the same subnet as my lights are on. I wasn't sure how to fix that issue so I've been adding the IPs manually.

I believe running Docker with the `--network host` switch (or setting `network: host` in a `docker-compose.yml` file) should do the trick. It will run the container on the host's IP address/network. *Caveat:* It has it's downsides thought, you then won't be able to connect as easily to other containers you're possibly running on the same network. It probably has some security implications also if you're running the container on a host that's accessable from the internet.

Also, if you happen to be running Node-RED on a Home Assistant OS, I have no clue if you can even change that.

Personally, I run pretty much everything related to my home automation in Docker containers but I prefer running Node-RED directly on the host. I guess it's mostly to give a bit more direct access for experimenting things.

**Comment by zenoran** [comment]
I appear to have resolved the issue.  Thank you for the discovery client; that helped troubleshoot.  My issue was directly related to my AP/router (UniFi) which was apparently blocking multicast capabilities as a default setting.

**Comment by ristomatti** [comment]
Thanks for the update.
