### ISSUE TITLE
Transfering NPM ownership

### ISSUE THREAD

**Issue by jdomeij** [ristomatti/node-red-contrib-node-lifx#6]
Hello, yes my lifx branch is mostly dead. 
I still have two Lifx lights but they stops responding after a while and flickers, most likely the heatshield is not properly attached. 

If you are willing I could transfer management of the NPM module into your hands, I only need an username

**Comment by ristomatti** [comment]
@jdomeij Hi! That would be be most excellent. Thank you for the trust and gesture. My NPM username is the same as on GitHub: **ristomatti**.

Please let me know any wishes for the future. For instance if you'd like the ownership transferred back in case I get tired of maintaining this?

Thank you again for reaching out!

**Comment by jdomeij** [comment]
No problems, I have added you as maintainer. 
I currently have no plan to maintain this module, I mostly did it because it was an fun project and there was no existing project to handle lifx using local connection.

**Comment by ristomatti** [comment]
Thank you!
